# Generated by Django 6.0.5 on 2026-05-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('provider', models.CharField(default='census', max_length=64)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['query'],
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=8)),
                ('rack_id', models.CharField(max_length=32)),
                ('retail_price', models.DecimalField(decimal_places=8, max_digits=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geocoding_status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('unmatched', 'Unmatched'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('geocoding_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('source_row_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'city', 'state'],
                'indexes': [models.Index(fields=['state', 'city'], name='fuel_fuelst_state_99cf3a_idx'), models.Index(fields=['is_active', 'latitude', 'longitude'], name='fuel_fuelst_is_acti_fcb361_idx'), models.Index(fields=['retail_price'], name='fuel_fuelst_retail__3784a3_idx'), models.Index(fields=['opis_truckstop_id'], name='fuel_fuelst_opis_tr_125a51_idx')],
            },
        ),
    ]
